#!/usr/bin/env bash

# check  if venv is activated
if [ -z "$VIRTUAL_ENV" ]; then
    echo "No virtual environment activated, activating..."
    source .venv/bin/activate
fi

export DYLD_FRAMEWORK_PATH=/System/Library/Frameworks
mjpython $@